### ISSUE TITLE
Page Infrastructure

### ISSUE THREAD

**Issue by OswaldHaidinger** [OswaldHaidinger/Movie-X-Shazam#1]
## Value proposition

As an Movie enthusiast
I want a web interface I can interact with.
So that I can learn about my favourite movie.

## Description

￼
![image](https://github.com/OswaldHaidinger/Movie-X-Shazam/assets/164864733/2fa6fa85-817e-4fc9-9fe1-c84dba9bfe9e)

Three screens: Record screen, loading screen and the Information screen.

## Acceptance criteria

- [ ] Three/Two Pages with basic design
- [ ] Dynamic Scene page with one layout for all.

## Tasks

- [ ] Build the frontend for 2/3 Pages 
- [ ] Make a dynamic Scene page using React
- [ ] reference the input to the database that is going to be build
