### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by OswaldHaidinger** [OswaldHaidinger/Movie-X-Shazam#2]
## Value proposition

As an Movie enthusiast 
I want a web page full of information about the movie.
So that I can learn any detail I want dive deeper into the movie.

## Description

￼
![image](https://github.com/OswaldHaidinger/Movie-X-Shazam/assets/164864733/adc22813-28cc-42ba-8c9e-4470504297ee)
- Create a database for one movie. Keep in mind that new movies will be added in the future.

## Acceptance criteria

- [ ] Data for the first 10 minutes of the movie
- [ ] Each sentence has a time stamp attached to it
- [ ] The infrastructure should be organised by scenes and contain all relevant background information

## Tasks

- [ ] Collect the script data and apply a time stamp to each sentence of the first 10 minutes of the movie
- [ ] Create the database infrastructure so that it is organised and quick to access.
- [ ] Fill the database with movie information (actors, location, clothing…)
