### ISSUE TITLE
#1 Speech to Text API Integration

### ISSUE THREAD

**Issue by OswaldHaidinger** [OswaldHaidinger/Movie-X-Shazam#3]
## Value proposition

As a Harry Potter enthusiast
I want to listen to the movie with my computer microphone
So that it can be transcribed and send to me

## Description

- Integrate the Text to Speech API, be able to use microphone for recording and receive text response from the API

<img width="1026" alt="image" src="https://github.com/OswaldHaidinger/Movie-X-Shazam/assets/164864733/214d641a-88c2-4152-b12f-570bcaa6c0dc">

## Acceptance criteria

1. On the start screen there is a button with the text "Record" which will start the recording for 10 seconds.
2. When it is clicked it starts recording
3. While it is recording, the color of the button is changing to indicate a response and it displays the text "Listening..."
4. Once the recording is over and is being processed by the API, change the color of the button again and write "Searching..."
5. When the response is returned, display the recorded text to show the user what was recorded
6. Below the text response, display a button with the text "Try Again" which will take you back to the start page 

## Tasks

- [ ] Create a new project file for the App
- [ ] Integrate the API so that is can receive the recorded audio
- [ ] Receive the response from the API as a string
